//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winkel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADMIN
    {
        public byte ADMINID { get; set; }
        public string ADMINNAME { get; set; }
        public string ADMINSURNAME { get; set; }
        public string ADMINEMAIL { get; set; }
        public string ADMINPASSWORD { get; set; }
    }
}
